CREATE TABLE civic_questionnaire_editions (
    id UUID PRIMARY KEY,
    version VARCHAR(40) NOT NULL UNIQUE,
    title_ar VARCHAR(180) NOT NULL,
    title_fr VARCHAR(180) NOT NULL,
    title_en VARCHAR(180) NOT NULL,
    intro_ar VARCHAR(1200) NOT NULL,
    intro_fr VARCHAR(1200) NOT NULL,
    intro_en VARCHAR(1200) NOT NULL,
    methodology_ar VARCHAR(2400) NOT NULL,
    methodology_fr VARCHAR(2400) NOT NULL,
    methodology_en VARCHAR(2400) NOT NULL,
    data_cutoff DATE NOT NULL,
    content_digest VARCHAR(80) NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED', 'SUPERSEDED')),
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE civic_questionnaire_themes (
    edition_id UUID NOT NULL REFERENCES civic_questionnaire_editions (id) ON DELETE CASCADE,
    code VARCHAR(48) NOT NULL,
    label_ar VARCHAR(120) NOT NULL,
    label_fr VARCHAR(120) NOT NULL,
    label_en VARCHAR(120) NOT NULL,
    sort_order INTEGER NOT NULL,
    PRIMARY KEY (edition_id, code),
    UNIQUE (edition_id, sort_order)
);

CREATE TABLE civic_questions (
    id UUID PRIMARY KEY,
    edition_id UUID NOT NULL REFERENCES civic_questionnaire_editions (id) ON DELETE CASCADE,
    question_key VARCHAR(64) NOT NULL,
    theme_code VARCHAR(48) NOT NULL,
    sort_order INTEGER NOT NULL,
    prompt_ar VARCHAR(700) NOT NULL,
    prompt_fr VARCHAR(700) NOT NULL,
    prompt_en VARCHAR(700) NOT NULL,
    context_ar VARCHAR(1600) NOT NULL,
    context_fr VARCHAR(1600) NOT NULL,
    context_en VARCHAR(1600) NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('DRAFT', 'REVIEWED', 'PUBLISHED')),
    FOREIGN KEY (edition_id, theme_code) REFERENCES civic_questionnaire_themes (edition_id, code),
    UNIQUE (edition_id, question_key),
    UNIQUE (edition_id, sort_order)
);

CREATE TABLE civic_question_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id UUID NOT NULL REFERENCES civic_questions (id) ON DELETE CASCADE,
    label_ar VARCHAR(240) NOT NULL,
    label_fr VARCHAR(240) NOT NULL,
    label_en VARCHAR(240) NOT NULL,
    source_url VARCHAR(1200) NOT NULL,
    source_date DATE,
    sort_order INTEGER NOT NULL DEFAULT 1,
    UNIQUE (question_id, source_url)
);

INSERT INTO civic_questionnaire_editions (
    id, version, title_ar, title_fr, title_en, intro_ar, intro_fr, intro_en,
    methodology_ar, methodology_fr, methodology_en, data_cutoff, content_digest,
    status, published_at
) VALUES (
    'c1000000-0000-4000-8000-000000000001',
    'morocco-priorities-2026-v1',
    'شنو مهم عندك فمغرب 2026؟',
    'Quelles sont vos priorités pour le Maroc en 2026 ?',
    'What matters to you for Morocco in 2026?',
    'جاوب على 18 سؤال باش تشوف الأولويات والاختيارات العمومية اللي كتعني ليك أكثر. هادي ماشي توصية انتخابية وما كترتب حتى حزب.',
    'Répondez à 18 questions pour faire ressortir vos priorités et les arbitrages publics qui comptent le plus pour vous. Ce profil ne recommande ni ne classe aucun parti.',
    'Answer 18 questions to surface the public priorities and trade-offs that matter most to you. This profile does not recommend or rank any party.',
    'النتيجة كتتحسب بقواعد واضحة من الأجوبة ديالك فقط. السؤال المتجاوز ما كيدخلش فالحساب، والسؤال اللي علمتيه كمهم كيتحسب بجوج. فهّمني ما كيخزنش الأجوبة ديال الزوار.',
    'Le résultat est calculé uniquement à partir de vos réponses avec des règles publiques. Une question passée est exclue et une question marquée importante compte double. Fhemni ne conserve pas les réponses anonymes.',
    'The result is calculated only from your answers using public rules. Skipped questions are excluded and questions marked important count twice. Fhemni does not retain anonymous answers.',
    DATE '2026-09-16',
    'sha256:morocco-priorities-2026-v1-reviewed',
    'PUBLISHED',
    CURRENT_TIMESTAMP
);

INSERT INTO civic_questionnaire_themes (edition_id, code, label_ar, label_fr, label_en, sort_order) VALUES
    ('c1000000-0000-4000-8000-000000000001', 'PURCHASING_POWER', 'الأسعار والقدرة الشرائية', 'Prix et pouvoir d''achat', 'Prices and purchasing power', 1),
    ('c1000000-0000-4000-8000-000000000001', 'EMPLOYMENT', 'الشغل والاقتصاد', 'Emploi et économie', 'Jobs and the economy', 2),
    ('c1000000-0000-4000-8000-000000000001', 'EDUCATION', 'التعليم', 'Éducation', 'Education', 3),
    ('c1000000-0000-4000-8000-000000000001', 'HEALTH', 'الصحة', 'Santé', 'Healthcare', 4),
    ('c1000000-0000-4000-8000-000000000001', 'WATER', 'الماء والمناخ', 'Eau et climat', 'Water and climate', 5),
    ('c1000000-0000-4000-8000-000000000001', 'SOCIAL_PROTECTION', 'الحماية الاجتماعية', 'Protection sociale', 'Social protection', 6),
    ('c1000000-0000-4000-8000-000000000001', 'GOVERNANCE', 'الحكامة والمؤسسات', 'Gouvernance et institutions', 'Governance and institutions', 7),
    ('c1000000-0000-4000-8000-000000000001', 'TERRITORIAL', 'المجال والنقل والسكن', 'Territoires, transport et logement', 'Places, transport and housing', 8),
    ('c1000000-0000-4000-8000-000000000001', 'EQUALITY', 'المساواة والمشاركة', 'Égalité et participation', 'Equality and participation', 9);

INSERT INTO civic_questions (
    id, edition_id, question_key, theme_code, sort_order,
    prompt_ar, prompt_fr, prompt_en, context_ar, context_fr, context_en, status
) VALUES
    ('c2000000-0000-4000-8000-000000000001', 'c1000000-0000-4000-8000-000000000001', 'targeted-subsidies', 'PURCHASING_POWER', 1,
     'خاص الدعم العمومي يمشي بالأساس للأسر اللي محتاجاه، حتى إلا تنقص الدعم العام على الأسعار.',
     'Les aides publiques devraient cibler en priorité les ménages qui en ont besoin, même si les subventions générales sur les prix diminuent.',
     'Public support should primarily target households that need it, even if broad price subsidies are reduced.',
     'الدعم الموجه كيقدر يوصل ميزانية أكثر للأسر الهشة، ولكن تحديد المستفيدين يقدر يخلي شي ناس محتاجين خارج النظام.',
     'Le ciblage peut concentrer davantage de moyens sur les ménages vulnérables, mais les critères peuvent exclure certaines personnes qui en ont besoin.',
     'Targeting can concentrate more support on vulnerable households, but eligibility rules can leave some people in need outside the system.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000002', 'c1000000-0000-4000-8000-000000000001', 'income-catch-up', 'PURCHASING_POWER', 2,
     'خاص الأجور الدنيا والمعاشات يطلعو باش يلحقو غلاء المعيشة، حتى إلا زادت الكلفة على المشغلين والميزانية.',
     'Les salaires minimums et les pensions devraient rattraper le coût de la vie, même si cela augmente le coût pour les employeurs et le budget public.',
     'Minimum wages and pensions should catch up with living costs, even if this raises costs for employers and the public budget.',
     'رفع المداخيل كيحمي القدرة الشرائية، ولكن السرعة والطريقة يقدرو يأثرو على التوظيف وتوازن المالية العمومية.',
     'La hausse des revenus protège le pouvoir d''achat, mais son rythme et sa méthode peuvent peser sur l''emploi et les finances publiques.',
     'Higher incomes protect purchasing power, but the pace and method can affect hiring and public finances.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000003', 'c1000000-0000-4000-8000-000000000001', 'essential-tax-relief', 'PURCHASING_POWER', 3,
     'خاص تنقص الضرائب على المواد والخدمات الأساسية، حتى إلا نقصات مداخيل الدولة لتمويل خدمات أخرى.',
     'Il faudrait réduire les taxes sur les biens et services essentiels, même si cela diminue les recettes qui financent d''autres services.',
     'Taxes on essential goods and services should be reduced, even if this lowers revenue for other public services.',
     'التخفيض يقدر ينقص الثمن بسرعة إلا وصل للمستهلك، ولكن كيحتاج مراقبة وبديل للمداخيل اللي غادي تضيع.',
     'La baisse peut réduire rapidement les prix si elle est transmise aux consommateurs, mais elle exige un suivi et une compensation des recettes perdues.',
     'A tax cut can lower prices quickly if it reaches consumers, but it needs monitoring and a way to replace lost revenue.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000004', 'c1000000-0000-4000-8000-000000000001', 'competition-prices', 'PURCHASING_POWER', 4,
     'الأولوية خاصها تكون لتقوية المنافسة وشفافية الأرباح والأسواق، ماشي لتحديد دائم ديال الأسعار.',
     'La priorité devrait aller à la concurrence et à la transparence des marges et des marchés plutôt qu''à un contrôle permanent des prix.',
     'Priority should go to stronger competition and transparent margins and markets rather than permanent price controls.',
     'إصلاح المنافسة كيعالج أسباب بنيوية ولكن النتائج كتحتاج الوقت؛ تحديد الأسعار يقدر يعطي راحة سريعة ولكن يخلق خصاص أو كلفة على الميزانية.',
     'La réforme de la concurrence traite les causes structurelles mais prend du temps ; le contrôle des prix peut soulager vite tout en créant pénuries ou coûts budgétaires.',
     'Competition reform addresses structural causes but takes time; price controls may offer quick relief while creating shortages or fiscal costs.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000005', 'c1000000-0000-4000-8000-000000000001', 'sme-jobs', 'EMPLOYMENT', 5,
     'خلق الشغل خاصو يعتمد أكثر على تسهيل نمو المقاولات الصغيرة والمتوسطة، ماشي أساسا على التوظيف العمومي.',
     'La création d''emplois devrait reposer davantage sur la croissance des PME que principalement sur le recrutement public.',
     'Job creation should rely more on helping small and medium businesses grow than mainly on public hiring.',
     'المقاولات تقدر تخلق شغل متنوع ودائم، ولكن خاص تمويل ومنافسة عادلة؛ التوظيف العمومي مباشر ولكن محدود بالميزانية.',
     'Les PME peuvent créer des emplois variés et durables, mais ont besoin de financement et d''une concurrence équitable ; l''emploi public est direct mais limité par le budget.',
     'Businesses can create varied, durable jobs but need finance and fair competition; public hiring is direct but constrained by the budget.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000006', 'c1000000-0000-4000-8000-000000000001', 'youth-apprenticeships', 'EMPLOYMENT', 6,
     'خاص التكوين بعد المدرسة يرتبط أكثر بالتدريب داخل المقاولات وحاجيات سوق الشغل.',
     'La formation après l''école devrait être davantage liée à l''apprentissage en entreprise et aux besoins du marché du travail.',
     'Post-school training should be tied more closely to apprenticeships and labour-market needs.',
     'الربط بالمقاولات يقدر يسهل أول فرصة للشباب، ولكن خاص ضمان جودة التكوين وما يتحولش ليد عاملة رخيصة.',
     'Le lien avec les entreprises peut faciliter le premier emploi, mais il faut garantir la qualité et éviter que l''apprentissage ne devienne du travail bon marché.',
     'Employer links can ease the first-job transition, but quality must be protected so apprenticeships do not become cheap labour.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000007', 'c1000000-0000-4000-8000-000000000001', 'women-work', 'EMPLOYMENT', 7,
     'خاص الاستثمار فالحضانات والنقل الآمن والحماية فالشغل يكون أولوية باش تزيد مشاركة النساء فالاقتصاد.',
     'L''investissement dans la garde d''enfants, le transport sûr et la protection au travail devrait être prioritaire pour accroître l''activité économique des femmes.',
     'Childcare, safe transport and workplace protection should be priorities for increasing women’s economic participation.',
     'هاد الخدمات كتزيل عوائق عملية على الشغل، ولكن كتطلب تمويل وتنسيق بين الدولة والمشغلين والجماعات.',
     'Ces services lèvent des obstacles concrets à l''emploi, mais exigent financement et coordination entre l''État, les employeurs et les collectivités.',
     'These services remove practical barriers to work, but require funding and coordination across government, employers and municipalities.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000008', 'c1000000-0000-4000-8000-000000000001', 'learning-accountability', 'EDUCATION', 8,
     'قبل بناء مؤسسات جديدة، خاص الأولوية تكون لقياس التعلمات ومحاسبة المسؤولين على النتائج داخل المدارس الحالية.',
     'Avant de construire de nouveaux établissements, la priorité devrait être de mesurer les apprentissages et de rendre les responsables comptables des résultats dans les écoles existantes.',
     'Before building new facilities, priority should go to measuring learning and holding leaders accountable for results in existing schools.',
     'تحسين النتائج كيحتاج معطيات ومواكبة للأساتذة؛ وفنفس الوقت بعض المناطق ما زالت محتاجة بنايات وتجهيزات.',
     'Améliorer les résultats exige des données et un accompagnement des enseignants, tandis que certaines zones ont encore besoin de bâtiments et d''équipements.',
     'Improving outcomes needs data and teacher support, while some areas still need buildings and equipment.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000009', 'c1000000-0000-4000-8000-000000000001', 'preschool-dropout', 'EDUCATION', 9,
     'خاص التعليم الأولي ومحاربة الهدر فالقرى ياخدو أولوية على توسيع التعليم الجامعي.',
     'Le préscolaire et la lutte contre le décrochage rural devraient être prioritaires par rapport à l''expansion de l''enseignement universitaire.',
     'Preschool and tackling rural dropout should take priority over expanding university education.',
     'التدخل بكري كيقدر ينقص الفوارق من الأصل، ولكن الجامعات حتى هي تحت ضغط وكتحتاج جودة ومقاعد أكثر.',
     'Agir tôt peut réduire les inégalités à la source, mais les universités sont aussi sous pression et ont besoin de qualité et de capacité.',
     'Early intervention can reduce inequality at its source, but universities also face pressure and need quality and capacity.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000010', 'c1000000-0000-4000-8000-000000000001', 'primary-care', 'HEALTH', 10,
     'خاص الموارد الصحية تمشي أولا للمراكز القريبة والأطباء والممرضين فالمناطق الناقصة، قبل المستشفيات الكبرى الجديدة.',
     'Les ressources de santé devraient d''abord renforcer les centres de proximité et le personnel dans les zones sous-dotées, avant de nouveaux grands hôpitaux.',
     'Health resources should first strengthen local clinics and staff in underserved areas before new large hospitals.',
     'العلاج القريب كيحل مشاكل كثيرة بكري ويخفف الضغط، ولكن الحالات المعقدة كتبقى محتاجة مستشفيات وتجهيزات متقدمة.',
     'Les soins de proximité traitent tôt de nombreux problèmes et réduisent la pression, mais les cas complexes nécessitent toujours des hôpitaux équipés.',
     'Local care addresses many problems early and reduces pressure, but complex cases still need advanced hospitals.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000011', 'c1000000-0000-4000-8000-000000000001', 'medicine-financing', 'HEALTH', 11,
     'خاص الدولة تفاوض بقوة على أثمنة الدوا وتوسع التمويل العمومي للعلاج، حتى إلا فرض هادشي مساهمات أو ضرائب أكثر.',
     'L''État devrait négocier fortement les prix des médicaments et élargir le financement public des soins, même si cela exige davantage de cotisations ou d''impôts.',
     'The state should negotiate medicine prices more strongly and expand public healthcare funding, even if this requires higher contributions or taxes.',
     'تمويل أوسع كيقلل الأداء من الجيب ويحمي الأسر، ولكن خاصو موارد دائمة وحكامة باش يبقى النظام قابل للاستمرار.',
     'Un financement plus large réduit les dépenses directes des ménages, mais exige des ressources durables et une bonne gouvernance.',
     'Broader funding lowers out-of-pocket costs, but needs durable revenue and governance to remain sustainable.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000012', 'c1000000-0000-4000-8000-000000000001', 'water-allocation', 'WATER', 12,
     'فوقت الجفاف، ماء الشرب والأنظمة الطبيعية خاصهم يسبقو الزراعات اللي كتستهلك الماء بزاف.',
     'En période de sécheresse, l''eau potable et les écosystèmes devraient passer avant les cultures très consommatrices d''eau.',
     'During drought, drinking water and ecosystems should take priority over water-intensive crops.',
     'هاد الاختيار كيحمي الحاجيات الأساسية والمخزون، ولكن يقدر يضر بمداخيل فلاحين ومناطق كتعيش من هاد الزراعات.',
     'Ce choix protège les besoins essentiels et les réserves, mais peut réduire les revenus des agriculteurs et des territoires dépendants de ces cultures.',
     'This protects essential needs and reserves, but can reduce income for farmers and areas dependent on those crops.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000013', 'c1000000-0000-4000-8000-000000000001', 'water-demand', 'WATER', 13,
     'خاص تدبير الطلب وتغيير الزراعات المسرفة يسبق الاعتماد الكبير على التحلية ونقل الماء.',
     'La gestion de la demande et le changement des cultures gourmandes en eau devraient précéder une forte dépendance au dessalement et aux transferts.',
     'Managing demand and changing water-intensive crops should come before heavy reliance on desalination and transfers.',
     'تقليص الطلب غالبا أقل كلفة، ولكن التحلية والربط بين الأحواض يقدرو يعطيو مورد إضافي للمدن والمناطق العطشانة.',
     'Réduire la demande coûte souvent moins cher, mais le dessalement et les transferts peuvent apporter une ressource supplémentaire aux zones en stress.',
     'Reducing demand often costs less, while desalination and transfers can add supply for water-stressed areas.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000014', 'c1000000-0000-4000-8000-000000000001', 'universal-protection', 'SOCIAL_PROTECTION', 14,
     'المغرب خاصو يمشي لضمانات اجتماعية أساسية للجميع، حتى إلا تطلبات ضرائب أو مساهمات أكثر.',
     'Le Maroc devrait aller vers des garanties sociales de base pour tous, même si cela exige davantage d''impôts ou de cotisations.',
     'Morocco should move toward basic social guarantees for everyone, even if this requires higher taxes or contributions.',
     'الشمول كيقلل الناس اللي كيسقطو بين الأنظمة وكيقوي التضامن، ولكن الكلفة كتفرض تمويل واضح وتدرج فالتطبيق.',
     'L''universalité réduit les personnes laissées entre les dispositifs et renforce la solidarité, mais son coût exige un financement clair et progressif.',
     'Universal coverage reduces gaps and strengthens solidarity, but its cost requires clear funding and gradual implementation.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000015', 'c1000000-0000-4000-8000-000000000001', 'public-transparency', 'GOVERNANCE', 15,
     'خاص الصفقات العمومية وتصريحات الممتلكات والمصالح تكون مفتوحة أكثر، حتى إلا ولات بعض القرارات أبطأ.',
     'Les marchés publics et les déclarations de patrimoine et d''intérêts devraient être plus ouverts, même si certaines décisions deviennent plus lentes.',
     'Public contracts and asset and interest declarations should be more open, even if some decisions become slower.',
     'الشفافية كتسهل المراقبة وتقلل تضارب المصالح، ولكن المساطر خاصها تبقى بسيطة باش ما توقفش التنفيذ.',
     'La transparence facilite le contrôle et réduit les conflits d''intérêts, mais les procédures doivent rester simples pour ne pas bloquer l''exécution.',
     'Transparency enables scrutiny and reduces conflicts of interest, but procedures must stay workable so delivery is not blocked.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000016', 'c1000000-0000-4000-8000-000000000001', 'regional-powers', 'GOVERNANCE', 16,
     'خاص الجهات والجماعات ياخدو صلاحيات وميزانيات أكثر، ومعاها محاسبة واضحة على النتائج.',
     'Les régions et les communes devraient recevoir davantage de pouvoirs et de budgets, avec une responsabilité claire sur les résultats.',
     'Regions and municipalities should receive more powers and budgets, with clear accountability for results.',
     'القرار القريب يقدر يناسب الحاجيات المحلية، ولكن الفوارق فالكفاءات بين الجهات تقدر توسع التفاوت إلا ما كانتش مواكبة.',
     'La décision de proximité peut mieux répondre aux besoins locaux, mais les écarts de capacité entre territoires peuvent creuser les inégalités sans accompagnement.',
     'Local decisions can fit local needs better, but uneven capacity across regions can widen inequality without support.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000017', 'c1000000-0000-4000-8000-000000000001', 'connected-territories', 'TERRITORIAL', 17,
     'الاستثمار فالنقل العمومي والسكن والخدمات فالمدن الصغيرة والقرى خاصو يسبق المشاريع الكبرى المركزة فالحواضر.',
     'L''investissement dans le transport public, le logement et les services des petites villes et zones rurales devrait passer avant les grands projets concentrés dans les métropoles.',
     'Public transport, housing and services in smaller cities and rural areas should take priority over major projects concentrated in big cities.',
     'توزيع الاستثمار كيخفف الفوارق والهجرة الاضطرارية، بينما المشاريع الكبرى تقدر تجيب نمو سريع وتخدم عدد كبير فمراكز الاقتصاد.',
     'Répartir l''investissement réduit les écarts et la migration contrainte, tandis que les grands projets peuvent accélérer la croissance dans les pôles économiques.',
     'Spreading investment reduces gaps and forced migration, while major projects can accelerate growth in economic centres.', 'PUBLISHED'),
    ('c2000000-0000-4000-8000-000000000018', 'c1000000-0000-4000-8000-000000000001', 'equality-care', 'EQUALITY', 18,
     'خاص إصلاحات المساواة الاقتصادية وتقاسم مسؤولية الرعاية تكون أولوية، حتى إلا طلبات تغييرات قانونية وميزانية إضافية.',
     'Les réformes pour l''égalité économique et le partage des responsabilités de soin devraient être prioritaires, même si elles exigent des changements juridiques et un budget supplémentaire.',
     'Economic-equality and shared-care reforms should be priorities, even if they require legal changes and additional public spending.',
     'المساواة فالقانون والخدمات تقدر توسع المشاركة والاختيار، ولكن التطبيق كيحتاج نقاش مجتمعي ومؤسسات قادرة تضمن الحقوق.',
     'L''égalité en droit et dans les services peut élargir la participation et le choix, mais sa mise en œuvre exige débat public et institutions capables de garantir les droits.',
     'Equality in law and services can widen participation and choice, but implementation needs public debate and institutions able to uphold rights.', 'PUBLISHED');

INSERT INTO civic_question_sources (question_id, label_ar, label_fr, label_en, source_url, source_date)
SELECT id, 'المندوبية السامية للتخطيط: مؤشر الأسعار يوليوز 2026', 'HCP : indice des prix, juillet 2026', 'HCP: consumer price index, July 2026',
       'https://www.hcp.ma/L-Indice-des-prix-a-la-consommation-IPC-du-mois-de-Juillet-2026_a4344.html', DATE '2026-07-31'
  FROM civic_questions WHERE question_key IN ('targeted-subsidies', 'income-catch-up', 'essential-tax-relief');

INSERT INTO civic_question_sources (question_id, label_ar, label_fr, label_en, source_url, source_date)
SELECT id, 'مجلس المنافسة: تتبع سوق المحروقات', 'Conseil de la concurrence : suivi du marché des carburants', 'Competition Council: fuel-market monitoring',
       'https://conseil-concurrence.ma/en/note-on-the-evolution-of-diesel-and-gasoline-prices-on-international-markets-and-their-impact-on-pump-prices-in-the-domestic-market-period-from-march-1-to-march-16-2026/', DATE '2026-03-16'
  FROM civic_questions WHERE question_key = 'competition-prices';

INSERT INTO civic_question_sources (question_id, label_ar, label_fr, label_en, source_url, source_date)
SELECT id, 'تقرير البارومتر العربي على المغرب', 'Rapport du Baromètre arabe sur le Maroc', 'Arab Barometer Morocco report',
       'https://www.arabbarometer.org/wp-content/uploads/AB8-Morocco-Report-ENG.pdf', DATE '2024-05-01'
  FROM civic_questions WHERE question_key IN ('sme-jobs', 'youth-apprenticeships', 'women-work', 'public-transparency');

INSERT INTO civic_question_sources (question_id, label_ar, label_fr, label_en, source_url, source_date)
SELECT id, 'المندوبية السامية للتخطيط: مؤشرات سوق الشغل', 'HCP : indicateurs du marché du travail', 'HCP: labour-market indicators',
       'https://www.hcp.ma/attachment/2897232/', DATE '2025-12-31'
  FROM civic_questions WHERE question_key IN ('learning-accountability', 'preschool-dropout', 'equality-care');

INSERT INTO civic_question_sources (question_id, label_ar, label_fr, label_en, source_url, source_date)
SELECT id, 'المجلس الاقتصادي والاجتماعي والبيئي: الولوج للعلاجات الأساسية', 'CESE : accès équitable aux soins de santé de base', 'CESE: equitable access to primary healthcare',
       'https://www.cese.ma/docs/soins-de-sante-de-base-vers-un-acces-equitable-et-generalise/', DATE '2025-01-01'
  FROM civic_questions WHERE question_key IN ('primary-care', 'medicine-financing');

INSERT INTO civic_question_sources (question_id, label_ar, label_fr, label_en, source_url, source_date)
SELECT id, 'البنك الدولي: الأمن المائي فالمغرب', 'Banque mondiale : sécurité hydrique au Maroc', 'World Bank: water security in Morocco',
       'https://www.worldbank.org/en/news/press-release/2023/07/24/new-world-bank-program-in-morocco-supports-efforts-to-boost-water-security-and-resilience-for-all', DATE '2023-07-24'
  FROM civic_questions WHERE question_key IN ('water-allocation', 'water-demand');

INSERT INTO civic_question_sources (question_id, label_ar, label_fr, label_en, source_url, source_date)
SELECT id, 'المجلس الاقتصادي والاجتماعي والبيئي: التقرير السنوي 2024', 'CESE : rapport annuel 2024', 'CESE: 2024 annual report',
       'https://www.cese.ma/media/2025/10/Rapport-annuel-2024-web-1.pdf', DATE '2025-10-01'
  FROM civic_questions WHERE question_key IN ('universal-protection', 'regional-powers', 'connected-territories');
