CREATE TABLE civic_party_positions (
    id UUID PRIMARY KEY,
    edition_id UUID NOT NULL REFERENCES civic_questionnaire_editions (id) ON DELETE CASCADE,
    question_id UUID NOT NULL REFERENCES civic_questions (id) ON DELETE CASCADE,
    party_code VARCHAR(16) NOT NULL,
    stance VARCHAR(16) NOT NULL CHECK (stance IN ('SUPPORTS', 'OPPOSES', 'MIXED', 'NO_POSITION')),
    evidence_summary_ar VARCHAR(800) NOT NULL,
    evidence_summary_fr VARCHAR(800) NOT NULL,
    evidence_summary_en VARCHAR(800) NOT NULL,
    editorial_status VARCHAR(16) NOT NULL CHECK (editorial_status IN ('DRAFT', 'REVIEWED', 'PUBLISHED')),
    reviewer_note VARCHAR(400),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    published_at TIMESTAMP WITH TIME ZONE,
    UNIQUE (edition_id, question_id, party_code)
);

CREATE TABLE civic_position_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id UUID NOT NULL REFERENCES civic_party_positions (id) ON DELETE CASCADE,
    promise_id UUID REFERENCES party_promises (id) ON DELETE SET NULL,
    label_ar VARCHAR(400) NOT NULL,
    label_fr VARCHAR(400) NOT NULL,
    label_en VARCHAR(400) NOT NULL,
    source_url VARCHAR(1200),
    page_reference VARCHAR(80),
    sort_order INTEGER NOT NULL DEFAULT 1,
    UNIQUE (position_id, promise_id)
);
